image:
  repository: tccr.io/truecharts/uptime-kuma
  pullPolicy: IfNotPresent
  tag: v1.17.0@sha256:a6f1ba6bef573ea359dd559c67501508efe40182a6ef5a8bbb74990156e671f7

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

security:
  PUID: 0

service:
  main:
    ports:
      main:
        port: 3001
        targetPort: 3001

persistence:
  config:
    enabled: true
    mountPath: "/app/data"
